p4_museum:
    resource: "@P4MuseumBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/museum
    requirements:
        _locale: en|fr

app:
    resource: '@AppBundle/Controller/'
    type: annotation
