<?php

namespace P4\MuseumBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

	public function countOrdersId($order)
  	{
	    $qb = $this->createQueryBuilder('o');
	    $qb
	      ->select('count(o.id)')
	      ->where('o.id = :order')
	      ->setParameter('order', $order);

	    return $qb->getQuery()->getSingleScalarResult();
  	}
}
