<?php

namespace P4\MuseumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * TicketownerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketownerRepository extends EntityRepository
{
	public function getTicketowners()
  	{
    $qb = $this->createQueryBuilder('t');

    $qb
    	->where('t.firstname = :firstname')
    	->setParameter('firstname', 'Arnaud');
    
    return $qb->getQuery()
			  ->getResult();

  	}
}
