<?php

namespace P4\MuseumBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

  public function countByValiditydate($validitydate)
  {
    $qb = $this->createQueryBuilder('t');
    $qb
      ->select('count(t.id)')
      ->where('t.validitydate = :validitydate')
      ->setParameter('validitydate', $validitydate);

    return $qb->getQuery()->getSingleScalarResult();
  }

  public function countByOrder($order)
  {
      $qb = $this->createQueryBuilder('t');
      $qb
        ->select('count(t.id)')
        ->where('t.orders = :orders')
        ->setParameter('orders', $order);

    return $qb->getQuery()->getSingleScalarResult();
  }

}
