services:
    p4_museum.validator.ticketlimit:                              
        class: P4\MuseumBundle\Validator\TicketlimitValidator     
        arguments: ["@doctrine.orm.entity_manager"] 
        tags:
            - { name: validator.constraint_validator, alias: p4_museum_ticketlimit }  

    p4_museum.validator.mailvalid:                              
        class: P4\MuseumBundle\Validator\MailvalidValidator     
        tags:
            - { name: validator.constraint_validator, alias: p4_museum_mailvalid }  

    p4_museum.validator.tuesdayvaliditydate:                              
        class: P4\MuseumBundle\Validator\TuesdayvaliditydateValidator     
        tags:
            - { name: validator.constraint_validator, alias: p4_museum_tuesdayvaliditydate } 

    p4_museum.validator.sundayvaliditydate:                              
        class: P4\MuseumBundle\Validator\SundayvaliditydateValidator     
        tags:
            - { name: validator.constraint_validator, alias: p4_museum_sundayvaliditydate }  

    p4_museum.validator.isclosed:                              
        class: P4\MuseumBundle\Validator\IsClosedValidator      
        tags:
            - { name: validator.constraint_validator, alias: p4_museum_isclosed } 

    p4_museum.validator.holidayticket:                              
        class: P4\MuseumBundle\Validator\HolidayticketValidator     
        tags:
            - { name: validator.constraint_validator, alias: p4_museum_holidayticket } 

    acme.twig.country_extension:
        class: P4\MuseumBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    app.request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory: 
            - '@request_stack'
            - 'getCurrentRequest'
            
    museum.ticket:
            class: P4\MuseumBundle\Service\TicketService
            autowire: false
            arguments:
                - '@session'
                - '@doctrine.orm.entity_manager'

    museum.mail:
            class: P4\MuseumBundle\Service\MailService
            autowire: false
            arguments:
                - '@mailer'
                - '@twig'

    museum.stripe:
            class: P4\MuseumBundle\Service\StripeService
            arguments:
                - '@session'
                - '@router'
                - '@app.request'
                - '@twig'
                - '@doctrine.orm.entity_manager'
                - '@translator'
                - '%stripe_secret_key%'
                - '@museum.mail'